name: Run Python script daily

on:
  schedule:
    - cron: "0 07 * * *"
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root
        poetry run playwright install chromium


    # 1️⃣ first run
    - name: Run script (first attempt)
      id: first_run
      env:
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      run: poetry run python main.py

    # 2️⃣ wait 6 mins, only if fail
    - name: Wait 6 minutes before retry
      if: failure()
      run: sleep 3600

    # 3️⃣ second run
    - name: Run script (retry)
      if: failure()
      env:
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      run: poetry run python main.py
