name: Run Python script daily

on:
  schedule:
    - cron: "0 07 * * 0"
    - cron: "0 08 * * 1"
    - cron: "0 06 * * 2"
    - cron: "0 09 * * 3"
    - cron: "0 06 * * 4"
    - cron: "0 07 * * 5"
    - cron: "0 08 * * 6"
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root
        poetry run playwright install chromium

    - name: Run script
      id: run
      env:
        EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        mongo_url: ${{ secrets.mongo_url }}
      run: poetry run python main.py
